### PR TITLE
Email field and custom callback added

### PR DESCRIPTION
**Pull request by avdyushin**
New features added:
E-mail field;
Hides addition content cell;
Callback to send mail via server API (if user have no email setup on device).

### CODE REVIEW

**Comment by rizumita** [comment]
I'm sorry for the delay.

Why doesn't the delegate method have additional content(image) argument?

**Comment by avdyushin** [comment]
Oh, it seems to be missed

**Comment by rizumita** [comment]
@avdyushin 
Please modify delegate method arguments.
I want the sample app not used delegate method because users can't understand what is done.
If you show an effect of delegate method, please add new feedback button on root view of the sample app.
If it is alright, please write how to use delegate method into README.md file.

**Comment by avdyushin** [comment]
I've added fixes to delegate and demo project

**Comment by rizumita** [comment]
Thank you for your nice job!
Because after I modified one line and resolved conflicts, I merged that with your commits, I close this PR.

**Comment by avdyushin** [comment]
Thanks

**Pull request closed without merging**
